#!/usr/bin/env python3
"""Turn bench_runner.py JSON files into the paper's LaTeX tables.

  python scripts/make_tables.py "results_*.json" --out tables.tex

Files are named results_<platform>_<rep>.json. Replicates of one platform (separate
CI jobs, possibly different VMs) are pooled: samples are concatenated, medians/CV/CI
recomputed, and the spread of the per-replicate ratio is reported. Every number comes
from raw samples; nothing is typed by hand.
"""
import argparse, glob, json, os, re, statistics, sys
sys.path.insert(0, os.path.dirname(__file__))
from bench_runner import median, cv, boot_ratio_ci   # noqa: E402

ORDER = ["fib", "float", "string", "sort", "array", "poly", "closure", "hash",
         "alloc", "macro", "macro_large", "io", "concurrent"]
CORE = ["fib", "float", "string", "sort", "array", "poly"]


def tex(s):
    return s.replace("&", r"\&").replace("_", r"\_")


def fmt_ms(x):
    return f"{x:.0f}" if x >= 100 else f"{x:.1f}"


def pool(runs):
    """runs: list of result dicts for the same platform -> pooled per-benchmark stats."""
    res = {}
    for b in ORDER:
        S, per = {}, {}
        for d in runs:
            e = d["results"].get(b)
            if not e: continue
            for k, v in e["samples"].items():
                S.setdefault(k, []).extend(v)
            if e.get("ratio_py"): per.setdefault("py", []).append(e["ratio_py"]["ratio"])
        if "bvm" not in S: continue
        ent = {"stat": {k: {"median": median(v), "cv": cv(v), "n": len(v)} for k, v in S.items() if v}}
        for base, key in (("py", "ratio_py"), ("lua", "ratio_lua")):
            if S.get("bvm") and S.get(base):
                lo, hi = boot_ratio_ci(S["bvm"], S[base])
                ent[key] = {"ratio": median(S["bvm"]) / median(S[base]), "lo": lo, "hi": hi}
        if S.get("base") and S.get("py"):
            lo, hi = boot_ratio_ci(S["base"], S["py"])
            ent["start"] = {"ratio": median(S["base"]) / median(S["py"]), "lo": lo, "hi": hi}
        if len(per.get("py", [])) > 1:
            ent["rep_spread"] = (min(per["py"]), max(per["py"]))
        res[b] = ent
    return res


def cell(r, bold_if_faster=True):
    if not r: return "--"
    s = f"{r['ratio']:.2f}"
    if bold_if_faster and r["hi"] < 1.0: s = r"\mathbf{" + s + "}"
    return f"${s}\\,[{r['lo']:.2f},{r['hi']:.2f}]$"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+")
    ap.add_argument("--out", default="tables.tex")
    a = ap.parse_args()
    files = sorted({f for p in a.files for f in glob.glob(p)})
    groups = {}
    for f in files:
        label = re.sub(r"^results_|_\d+\.json$|\.json$", "", os.path.basename(f))
        groups.setdefault(label, []).append(json.load(open(f)))
    pooled = {l: pool(rs) for l, rs in groups.items()}
    out = ["% --- generated by scripts/make_tables.py; do not edit ---", ""]

    out.append("% ===== environment =====")
    out.append("\\begin{tabular}{@{}lllllr@{}}\\toprule")
    out.append("Platform & CPU & CPython & Cores & Replicates & $n$/engine \\\\\\midrule")
    for l, rs in groups.items():
        e = rs[0]["env"]
        out.append(f"{tex(l)} & {tex(e['cpu'])} & {e['python']} & {e['cores']} & {len(rs)} & {e['n'] * len(rs)} \\\\")
    out.append("\\bottomrule\\end{tabular}\n")

    for l, res in pooled.items():
        out.append(f"% ===== {l}: ratio to CPython / gopher-lua / campaign start =====")
        out.append("\\begin{tabular}{@{}lrrrrrr@{}}\\toprule")
        out.append("Benchmark & CPython (ms) & Interp.\\ (ms) & CV & vs.\\ CPython [95\\% CI] & vs.\\ Lua [95\\% CI] & Start/CPython \\\\\\midrule")
        for b in ORDER:
            e = res.get(b)
            if not e: continue
            st = e["stat"]
            py = fmt_ms(st["py"]["median"]) if "py" in st else "--"
            start = f"${e['start']['ratio']:.2f}$" if "start" in e else "--"
            out.append(f"{tex(b)} & {py} & {fmt_ms(st['bvm']['median'])} & {st['bvm']['cv']:.0f}\\% & "
                       f"{cell(e.get('ratio_py'))} & {cell(e.get('ratio_lua'))} & {start} \\\\")
        out.append("\\bottomrule\\end{tabular}\n")

    out.append("% ===== cross-platform summary (ratio to CPython, pooled medians) =====")
    labels = list(pooled)
    out.append(f"\\begin{{tabular}}{{@{{}}l{'r' * len(labels)}@{{}}}}\\toprule")
    out.append("Benchmark & " + " & ".join(tex(l) for l in labels) + " \\\\\\midrule")
    for b in ORDER:
        cells = []
        for l in labels:
            r = pooled[l].get(b, {}).get("ratio_py")
            cells.append(f"${r['ratio']:.2f}$" if r else "--")
        if any(c != "--" for c in cells):
            out.append(tex(b) + " & " + " & ".join(cells) + " \\\\")
    out.append("\\bottomrule\\end{tabular}\n")

    out.append("% ===== summary statistics =====")
    for l, res in pooled.items():
        core = [res[b]["ratio_py"]["ratio"] for b in CORE if b in res and "ratio_py" in res[b]]
        allr = [res[b]["ratio_py"]["ratio"] for b in ORDER if b in res and "ratio_py" in res[b]]
        starts = [res[b]["start"]["ratio"] for b in CORE if b in res and "start" in res[b]]
        spreads = [(res[b]["rep_spread"][1] / res[b]["rep_spread"][0] - 1) * 100
                   for b in ORDER if b in res and "rep_spread" in res[b]]
        gm = lambda v: statistics.geometric_mean(v) if v else float("nan")
        out.append(f"% {l}: geomean ratio core={gm(core):.2f} all={gm(allr):.2f} "
                   f"min={min(allr):.2f} max={max(allr):.2f} "
                   + (f"start range={min(starts):.2f}-{max(starts):.2f} " if starts else "")
                   + (f"max replicate spread={max(spreads):.1f}%" if spreads else ""))
    open(a.out, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
