#!/usr/bin/env python3
"""Turn bench_runner.py JSON files into the paper's LaTeX tables.

  python scripts/make_tables.py "results_*.json" --out tables.tex --outdir tables/

Files are named results_<platform>_<rep>.json. Replicates of one platform are separate
CI jobs and may land on different CPUs (GitHub assigns hosts freely), so samples are NOT
pooled. Each replicate keeps its own statistics; the platform value is the median over
replicates and the bracket is the envelope of every replicate's 95% bootstrap CI (so it
covers within-job noise AND between-VM variation). Every number comes from raw samples.
"""
import argparse, glob, json, os, re, statistics, sys

ORDER = ["fib", "float", "string", "sort", "array", "poly", "closure", "hash",
         "alloc", "macro", "macro_large", "io", "concurrent"]
CORE = ["fib", "float", "string", "sort", "array", "poly"]
median = statistics.median
SHORT = {"linux-x86_64": "x86", "linux-arm64": "ARM", "macos-arm64": "mac", "windows-x86_64": "Win",
         "linux-x86_64-py311": "x86/3.11", "linux-x86_64-py313": "x86/3.13"}


def short_cpu(c):
    return re.sub(r" \d+-Core Processor", "", c).replace(" with Radeon Graphics", "")


def tex(s):
    return s.replace("&", r"\&").replace("_", r"\_")


def fmt_ms(x):
    return f"{x:.0f}" if x >= 100 else f"{x:.1f}"


def pool(runs):
    res = {}
    for b in ORDER:
        es = [d["results"][b] for d in runs if b in d["results"] and "bvm" in d["results"][b]]
        if not es:
            continue
        ent = {"stat": {}}
        for k in ("bvm", "py", "lua", "base"):
            xs = [e[k] for e in es if k in e]
            if xs:
                ent["stat"][k] = {"median": median([x["median"] for x in xs]),
                                  "cv": median([x["cv"] for x in xs])}
        for src, key in (("ratio_py", "ratio_py"), ("ratio_lua", "ratio_lua"),
                         ("ratio_start", "start")):
            rs = [e[src] for e in es if src in e]
            if rs:
                ent[key] = {"ratio": median([r["ratio"] for r in rs]),
                            "lo": min(r["ci_lo"] for r in rs),
                            "hi": max(r["ci_hi"] for r in rs),
                            "all": [r["ratio"] for r in rs]}
        if len(es) > 1 and "ratio_py" in ent:
            res_all = ent["ratio_py"]["all"]
            ent["rep_spread"] = (min(res_all), max(res_all))
        res[b] = ent
    return res


def cell(r):
    if not r:
        return "--"
    s = f"{r['ratio']:.2f}"
    if r["hi"] < 1.0:
        s = r"\mathbf{" + s + "}"          # significantly faster than the baseline
    return f"${s}\\,[{r['lo']:.2f},{r['hi']:.2f}]$"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+")
    ap.add_argument("--out", default="tables.tex")
    ap.add_argument("--outdir", help="also write one .tex per table (env, res_<platform>, summary, stats)")
    a = ap.parse_args()
    files = sorted({f for p in a.files for f in glob.glob(p)})
    loaded = []
    groups = {}
    gosens = {}
    ladder = {}
    pyver = {}
    for f in files:
        d = json.load(open(f))
        base = os.path.basename(f)
        label = re.sub(r"^results_|_\d+\.json$|\.json$", "", base)
        rep = re.search(r"_(\d+)\.json$", base)
        if label.startswith("pyver-"):            # CPython-version study (same VM per replicate)
            pyver.setdefault(label[6:], []).append(d)
            continue
        if label.startswith("lad-"):              # attribution ladder runs
            ladder.setdefault(label[4:], []).append(d)
            continue
        if label.startswith("go-"):               # toolchain-sensitivity runs: separate table
            gosens.setdefault(label[3:], []).append(d)
            continue
        loaded.append((label, rep.group(1) if rep else "1", d))
        groups.setdefault(label, []).append(d)
    pooled = {l: pool(rs) for l, rs in groups.items()}
    out = ["% --- generated by scripts/make_tables.py; do not edit ---", ""]
    blocks = {}

    # ---- environment: one row per platform; the CPU of every replicate exactly as the runner reports it
    mark = len(out)
    out.append("% ===== environment (one row per platform; CPUs of the replicates in order) =====")
    out.append("\\begin{tabular}{@{}llrr@{}}\\toprule")
    out.append("Platform & CPU of each replicate (as reported) & Cores & CPython / Go \\\\\\midrule")
    byl = {}
    for label, rep, d in loaded:
        byl.setdefault(label, []).append(d)
    for label, ds in byl.items():
        e0 = ds[0]["env"]
        names = [short_cpu(d["env"]["cpu"]).replace("AMD EPYC ", "").replace(" (Virtual)", "") for d in ds]
        cpus = f"{names[0]} $\\times${len(names)}" if len(set(names)) == 1 else ", ".join(names)
        fam = "AMD EPYC " if "EPYC" in e0["cpu"] else ""
        out.append(f"{tex(label)} & {tex(fam + cpus)} & {e0['cores']} & {e0['python']} / {e0.get('go', '1.25.3')} \\\\")
    out.append("\\bottomrule\\end{tabular}\n")
    blocks["env"] = out[mark:]

    # ---- per-platform detail
    for l, res in pooled.items():
        mark = len(out)
        out.append(f"% ===== {l}: ratio to CPython / gopher-lua / campaign start =====")
        out.append("\\begin{tabular}{@{}lrrrrrr@{}}\\toprule")
        out.append("Benchmark & CPython (ms) & Interp.\\ (ms) & CV & vs.\\ CPython & vs.\\ Lua & Start/CPython \\\\\\midrule")
        for b in ORDER:
            e = res.get(b)
            if not e:
                continue
            st = e["stat"]
            py = fmt_ms(st["py"]["median"]) if "py" in st else "--"
            start = f"${e['start']['ratio']:.2f}$" if "start" in e else "--"
            out.append(f"{tex(b)} & {py} & {fmt_ms(st['bvm']['median'])} & {st['bvm']['cv']:.0f}\\% & "
                       f"{cell(e.get('ratio_py'))} & {cell(e.get('ratio_lua'))} & {start} \\\\")
        out.append("\\bottomrule\\end{tabular}\n")
        blocks["res_" + l] = out[mark:]

    # ---- cross-platform summary
    mark = len(out)
    PREF = ['linux-x86_64', 'linux-arm64', 'macos-arm64', 'windows-x86_64', 'linux-x86_64-py311', 'linux-x86_64-py313']
    labels = sorted(pooled, key=lambda l: PREF.index(l) if l in PREF else 99)
    out.append("% ===== cross-platform summary (median over replicates of ratio to CPython) =====")
    out.append(f"\\begin{{tabular}}{{@{{}}l{'r' * len(labels)}@{{}}}}\\toprule")
    out.append("Benchmark & " + " & ".join(tex(SHORT.get(l, l)) for l in labels) + " \\\\\\midrule")
    for b in ORDER:
        cells = []
        for l in labels:
            r = pooled[l].get(b, {}).get("ratio_py")
            cells.append(f"${r['ratio']:.2f}$" if r else "--")
        if any(c != "--" for c in cells):
            out.append(tex(b) + " & " + " & ".join(cells) + " \\\\")
    out.append("\\bottomrule\\end{tabular}\n")
    blocks["summary"] = out[mark:]

    # ---- ratio to gopher-lua (the in-Go interpreter control), 3.12.10 platforms only
    mark = len(out)
    lab4 = [l for l in labels if "py3" not in l]
    out.append("% ===== ratio to gopher-lua (median over replicates) =====")
    out.append(f"\\begin{{tabular}}{{@{{}}l{'r' * len(lab4)}@{{}}}}\\toprule")
    out.append("Workload & " + " & ".join(tex(SHORT.get(l, l)) for l in lab4) + " \\\\\\midrule")
    for b in ORDER:
        cells = []
        for l in lab4:
            r = pooled[l].get(b, {}).get("ratio_lua")
            cells.append((f"$\\mathbf{{{r['ratio']:.2f}}}$" if r["hi"] < 1.0 else f"${r['ratio']:.2f}$") if r else "--")
        if any(c != "--" for c in cells):
            out.append(tex(b) + " & " + " & ".join(cells) + " \\\\")
    out.append("\\bottomrule\\end{tabular}\n")
    blocks["lua"] = out[mark:]

    # ---- Go toolchain sensitivity: alt (newer Go) / base (Go 1.25.3), same VM, same source
    if gosens:
        mark = len(out)
        gl = sorted(gosens)
        out.append("% ===== Go toolchain sensitivity: time(alt toolchain) / time(reference toolchain) =====")
        out.append(f"\\begin{{tabular}}{{@{{}}l{'r' * len(gl)}@{{}}}}\\toprule")
        out.append("Benchmark & " + " & ".join(tex(SHORT.get(l, l)) for l in gl) + " \\\\\\midrule")
        gm_cells, summ = [], []
        for b in ORDER:
            cells = []
            for l in gl:
                rs = [d["results"][b]["ratio_alt"]["ratio"] for d in gosens[l]
                      if b in d["results"] and "ratio_alt" in d["results"][b]]
                cells.append(f"${median(rs):.2f}$" if rs else "--")
            if any(c != "--" for c in cells):
                out.append(tex(b) + " & " + " & ".join(cells) + " \\\\")
        for l in gl:
            vals = [median([d["results"][b]["ratio_alt"]["ratio"] for d in gosens[l]
                            if b in d["results"] and "ratio_alt" in d["results"][b]])
                    for b in ORDER if any(b in d["results"] and "ratio_alt" in d["results"][b] for d in gosens[l])]
            gm_cells.append(f"${statistics.geometric_mean(vals):.2f}$" if vals else "--")
            summ.append(f"% go-sens {l}: geomean alt/base={statistics.geometric_mean(vals):.2f} min={min(vals):.2f} max={max(vals):.2f}")
        out.append("\\midrule")
        out.append("geomean & " + " & ".join(gm_cells) + " \\\\")
        out.append("\\bottomrule\\end{tabular}\n")
        out.extend(summ)
        blocks["gosens"] = out[mark:]

    # ---- attribution ladder: per-commit binaries built and run in CI
    if ladder:
        STEPS = {"L1_stackptr": "Fused branch-pop, explicit stack ptr., in-place arithmetic",
                 "L2_fusion": "Local/array-field fused compares and jumps",
                 "L3_preinline": "Review fixes and refactors (no perf. intent)",
                 "L4_inline": "Inline-budget reshaping + dispatch caches",
                 "L5_memo_fast": "Fast constructors, array fusions, constant memo., EQ path",
                 "L6_dense": "Value repack + dense primitive arrays",
                 "L7_frames": "Recovery: code mirror in frame, fast return, cheaper frame pool",
                 "L8_calls_pgo": "Recovery: fast call path, ASCII string paths, PGO profile",
                 "L9_constops": "Recovery: fused CONSTANT+arithmetic, instance-pool cache",
                 "L10_strings_eq": "Recovery: string concat and equality fast paths",
                 "L11_memory": "Memory: Value 48 B, one-allocation instances, scalar stores"}
        COLS = ["fib", "float", "string", "sort", "array", "poly", "closure", "hash", "alloc"]
        for plat, rs in ladder.items():
            mark = len(out)
            out.append(f"% ===== attribution ladder ({plat}): % change in run time vs. previous step =====")
            out.append("\\begin{tabular}{@{}l" + "r" * len(COLS) + "@{}}\\toprule")
            out.append("Step & " + " & ".join(tex(c) for c in COLS) + " \\\\\\midrule")
            tot = {c: 1.0 for c in COLS}
            for step, label in STEPS.items():
                cells = []
                for c in COLS:
                    vals = []
                    sig = True
                    for d in rs:
                        row = next((r for r in d["results"].get(c, {}).get("ladder", []) if r["name"] == step), None)
                        if row and "vs_prev" in row:
                            vals.append(row["vs_prev"]["ratio"])
                            sig = sig and (row["vs_prev"]["ci_hi"] < 1.0 or row["vs_prev"]["ci_lo"] > 1.0)
                    if vals:
                        m = median(vals); tot[c] *= m
                        pct = (m - 1) * 100
                        cells.append((f"$\mathbf{{{pct:+.0f}}}$" if sig else f"${pct:+.0f}$").replace("+", "{+}"))
                    else:
                        cells.append("--")
                out.append(f"{tex(label)} & " + " & ".join(cells) + " \\\\")
            out.append("\\midrule")
            out.append("Total (start $\\to$ final) & " + " & ".join(f"${(tot[c]-1)*100:+.0f}$".replace("+", "{+}") for c in COLS) + " \\\\")
            out.append("\\bottomrule\\end{tabular}\n")
            blocks["attrib_" + plat] = out[mark:]

    # ---- CPython-version study: three versions measured in the same VM, per replicate
    if pyver:
        mark = len(out)
        vers = sorted(pyver)
        out.append("% ===== CPython version study (ratio to CPython; each replicate ran all versions on one VM) =====")
        out.append("\\begin{tabular}{@{}l" + "r" * len(vers) + "r@{}}\\toprule")
        out.append("Benchmark & " + " & ".join(f"{v}" for v in vers) + " & max chg. \\\\\\midrule")
        per = {v: pool(pyver[v]) for v in vers}
        swing = {}
        for b in ORDER:
            rs = [per[v].get(b, {}).get("ratio_py") for v in vers]
            if not all(rs):
                continue
            vals = [r["ratio"] for r in rs]
            swing[b] = max(vals) / min(vals) - 1
            out.append(tex(b) + " & " + " & ".join(f"${r['ratio']:.2f}$" for r in rs)
                       + f" & ${swing[b] * 100:.0f}\\%$ \\\\")
        gms = []
        for v in vers:
            allr = [per[v][b]["ratio_py"]["ratio"] for b in ORDER if b in per[v] and "ratio_py" in per[v][b]]
            gms.append(statistics.geometric_mean(allr))
        out.append("\\midrule")
        out.append("geomean (all) & " + " & ".join(f"${g:.2f}$" for g in gms) + " & \\\\")
        gms2 = []
        for v in vers:
            ex = [per[v][b]["ratio_py"]["ratio"] for b in ORDER
                  if b in per[v] and "ratio_py" in per[v][b] and b not in ("string", "concurrent")]
            gms2.append(statistics.geometric_mean(ex))
        out.append("geomean (excl.) & " + " & ".join(f"${g:.2f}$" for g in gms2) + " & \\\\")
        out.append("\\bottomrule\\end{tabular}\n")
        out.append("% pyver: " + " ".join(f"{v}: all={g:.2f} excl={g2:.2f}" for v, g, g2 in zip(vers, gms, gms2))
                   + f" max-swing={max(swing.values()) * 100:.0f}% ({max(swing, key=swing.get)})")
        out.append("% pyver replicates: " + ", ".join(f"{v}:{len(pyver[v])}" for v in vers))
        blocks["pyver"] = out[mark:]

    # ---- peak memory (RSS / peak working set), interpreter relative to CPython and to gopher-lua
    mark = len(out)
    lab4m = [l for l in labels if "py3" not in l]
    rows = []
    for b in ORDER:
        cells, any_ = [], False
        for l in lab4m:
            vals = [d["results"][b]["mem_ratio_py"] for d in groups[l]
                    if b in d["results"] and "mem_ratio_py" in d["results"][b]]
            cells.append(f"${median(vals):.2f}$" if vals else "--")
            any_ = any_ or bool(vals)
        if any_:
            rows.append(tex(b) + " & " + " & ".join(cells) + " \\\\")
    if rows:
        out.append("% ===== peak memory: interpreter / CPython (median over replicates) =====")
        out.append(f"\\begin{{tabular}}{{@{{}}l{'r' * len(lab4m)}@{{}}}}\\toprule")
        out.append("Workload & " + " & ".join(tex(SHORT.get(l, l)) for l in lab4m) + " \\\\\\midrule")
        out.extend(rows)
        gms = []
        for l in lab4m:
            vs = [median([d["results"][b]["mem_ratio_py"] for d in groups[l]
                          if b in d["results"] and "mem_ratio_py" in d["results"][b]] or [float("nan")])
                  for b in ORDER]
            vs = [v for v in vs if v == v]
            gms.append(f"${statistics.geometric_mean(vs):.2f}$" if vs else "--")
        out.append("\\midrule")
        out.append("geomean & " + " & ".join(gms) + " \\\\")
        out.append("\\bottomrule\\end{tabular}\n")
        blocks["mem"] = out[mark:]

    # ---- plain statistics for the prose
    mark = len(out)
    out.append("% ===== summary statistics (for prose) =====")
    gm = lambda v: statistics.geometric_mean(v) if v else float("nan")
    for l, res in pooled.items():
        core = [res[b]["ratio_py"]["ratio"] for b in CORE if b in res and "ratio_py" in res[b]]
        allr = {b: res[b]["ratio_py"]["ratio"] for b in ORDER if b in res and "ratio_py" in res[b]}
        starts = [res[b]["start"]["ratio"] for b in CORE if b in res and "start" in res[b]]
        spreads = [(res[b]["rep_spread"][1] / res[b]["rep_spread"][0] - 1) * 100
                   for b in ORDER if b in res and "rep_spread" in res[b]]
        faster = sorted(b for b, r in allr.items() if res[b]["ratio_py"]["hi"] < 1.0)
        slower = sorted(b for b, r in allr.items() if res[b]["ratio_py"]["lo"] > 1.0)
        ex = [r for b, r in allr.items() if b not in ("string", "concurrent")]
        out.append(f"% {l}: geomean core={gm(core):.2f} all={gm(list(allr.values())):.2f} excl-str-conc={gm(ex):.2f} "
                   f"min={min(allr.values()):.2f} max={max(allr.values()):.2f} "
                   f"faster(CI<1)={','.join(faster)} slower(CI>1)={','.join(slower)} "
                   + (f"start={min(starts):.2f}-{max(starts):.2f} " if starts else "")
                   + (f"max-rep-spread={max(spreads):.0f}% median-rep-spread={median(spreads):.0f}%" if spreads else ""))
    blocks["stats"] = out[mark:]

    open(a.out, "w", encoding="utf-8").write("\n".join(out) + "\n")
    if a.outdir:
        os.makedirs(a.outdir, exist_ok=True)
        for k, v in blocks.items():
            open(os.path.join(a.outdir, k + ".tex"), "w", encoding="utf-8").write("\n".join(v) + "\n")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
